### PR TITLE
enable custom builds with ignored components

### PR DESCRIPTION
**Pull request by troyk**
components can be ignored by passing their names to the --ignore command line argument
ex: `gulp --ignore carousel,scrollspy`

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Going to give the changes a look atm. :)

**Comment by IngwiePhoenix** [comment]
`srcDir + "...file.js"` is good, but using `path.join()` would ensure the paths are properly connected with the system's path separator. Other than that, this looks pretty good, imho.

**Comment by troyk** [comment]
@IngwiePhoenix @thednp thanks guys, I don't do much server-side js but I'm off to Gulp all the things on some of my other projects ;)

**Comment by thednp** [comment]
No, I thank you. Awesome.

**Comment by thednp** [comment]
@troyk will you help me develop a similar functionality for my [KUTE.js](https://github.com/thednp/kute.js) please?

**Pull request merged**
