### PR TITLE
Collapse fixes

### PR DESCRIPTION
**Pull request by soda0289**
I have noticed some issues with Collapse and how it calculates max height and resizes the div. The current getMaxHeight function doesn't take in to account padding of the collapsible div and returns and incorrect height. Also, in Firefox, when a dropdown select form element is present it can't be used as it disappears when the style attribute and class is modified. This was resolved by adding a current height variable and only calling resize when maxHeight changes for the div.

An example of these problems can be seen here:
http://codepen.io/anon/pen/MaMwgW

### CODE REVIEW

**Comment by thednp** [comment]
Thanks for the commit. The check for height readjust on resize is a good idea, but the other isn't because we're using `el.clientHeight` which returns the element's height as viewed on screen, so it does include the padding. 

Think of the padding as a way to add spacing to an element's "inner content" if I can call it like that, while the height css is the height without the padding, but go ahead play some CSS (I did) and will enlighten you real quick: `el.clientHeight = el.computedStyle.height + el.computedStyle.paddingTop + el.computedStyle.paddingBottom`. I did.

**Comment by soda0289** [comment]
Are you referring to adding in the padding to height variable? Here is the code with pure bootstrap/jquery and it includes the padding somehow:
http://codepen.io/anon/pen/ojrzGL

I'm trying to step through it with the debugger but it seems to use scrollHeight property (https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight) but that does not include padding from what I can tell.

**Comment by thednp** [comment]
Taking padding into account isn't right, because we use `element.clientHeight` to determine the height, it kinda includes the padding, try for yourself.

**Comment by soda0289** [comment]
Yes after reading some documentation element.clientHeight is equal to the CSS height + CSS padding. However the current code only checks the children's clientHeight + CSS margins and not the padding/clientHeight of the collapsible div itself. A simpler solution than mine would be too add the collapsible elements clientHeight when getMaxHeight() is called.

Another solution is to use the element.scrollHeight, of the collapsible div, instead. We'd have to add the CSS style "overflow-y: hidden;"  for this property to generate the correct height with padding. Do you believe this a better solution than looping through all the child elements and adding clientHeights and CSS margins together?

**Comment by thednp** [comment]
The padding isn't gonna go, it's that simple, that commit will not go through.

**Comment by soda0289** [comment]
How should the problem be fixed then. If the padding isn't taken into account the div cuts off the bottom content. This doesn't happen when using Collapse from Bootstrap with JQuery.

**Comment by thednp** [comment]
There is no issue in the first place once you have the proper HTML structure. Just don't use content inside collapse elements that have or use padding. There's no need for it.

**Comment by soda0289** [comment]
I can remove the padding in my own code. I just thought this project was suppose to have the same features and work the same way as Bootstrap with JQuery.

Thanks anyways it's still a great project!

**Comment by thednp** [comment]
I didn't check the original code on this matter, I just know this is the right approach, especially dealing with legacy browsers as well. 

I believe the original plugin uses jQuery's (1.9) capability to deal with computed height PLUS padding to determine the height of collapse elements, while here we have native Javascript, again taking into account the legacy browsers. I hope this is super clear now :)

**Comment by soda0289** [comment]
I never tested on legacy browser I only target IE 8 and newer. I'll look into this more when I have some free time.

Thanks.

**Comment by thednp** [comment]
I've changed how collapse works, basically it works exactly like jQuery's `slideToggle` now, and it doesn't need to resize the collapses anymore, but leaves their height to their default value (`auto` in most cases).
https://github.com/thednp/bootstrap.native/commit/7600c97b97b33134992b816d83008f1adfd9d016

**Comment by soda0289** [comment]
Thanks for taking the time to fix this properly. It works as expected now. There is one issue in IE8 where if borderTopWidth is equal to a string, such as medium, thin or thick, the return value of getOuterHeight() is NaN. This then causes getMaxHeight to return NaN and throw an error when setting elem.style.height. I can send a patch or create an issue if you like but it's no big deal really just a minor issue I've seen in testing.

Thanks again!

**Comment by thednp** [comment]
Thanks for reporting that @soda0289, I will have a look at IE8 asap.

**Comment by thednp** [comment]
A quick question: are you using the polyfill or my own minifill? If not give it a try, but I already have a better idea how to deal with this.

**Comment by soda0289** [comment]
I use quite a few polyfills currently so this might be my issue.

**Comment by thednp** [comment]
make sure they include `getComputedStyle`

**Comment by thednp** [comment]
Hey I just got home and tested IE8 (with my minifill, which is mostly code from the polyfill service) and there is no issue, Collapse works perfect, with no issue whatsoever, so the polyfills you use aren't complete or at least don't includet the `window.getComputedStyle`.

**Comment by soda0289** [comment]
I have switched to using your polyfills/minifill and code works as expected. Thanks!

**Pull request closed without merging**
