### PR TITLE
Feat: support collapse in dropdown

### PR DESCRIPTION
**Pull request by jcorporation**
This patch enables collapse elements in dropdowns
- Adds all "A" child elements to menulist
- Skips hidden elements for keyboard navigation

### CODE REVIEW

**Comment by thednp** [comment]
Sup @jcorporation do you have an example to showcase the fix/improvement you propose? 

Thank you and sorry for the late reply.

**Comment by jcorporation** [comment]
I use collapse in dropdowns for the main menu in the left top in my project: https://github.com/jcorporation/myMPD.

This patch only enables keyboard navigation for collapse elements in dropdowns.

**Comment by thednp** [comment]
Is this feature supported by original plugins?

**Comment by thednp** [comment]
I guess not.

**Comment by jcorporation** [comment]
I don't know it. I only use your plugin and I thought it can be a useful feature also for others.

**Comment by thednp** [comment]
We usually have a general discussion in the Issues section about new features, because we want to keep the code simple and flexible. Simple code makes easy maintenance.

As in your case you can fork the project and use your version for your specific case, as the community haven't had any input in this development.

**Pull request closed without merging**
