### PR TITLE
Don't execute 'show()' when clicking on the active tab.

### PR DESCRIPTION
**Pull request by jpapillon**
Resolving issue #187

### CODE REVIEW

**Comment by Vuurvlieg** [comment]
Awesome, thanks for fixing!

**Comment by jpapillon** [comment]
@Vuurvlieg A new version needs to be release by @thednp for this to work.

**Comment by thednp** [comment]
@Vuurvlieg you can test code from his fork so we can know what we're dealin with here.

**Comment by Vuurvlieg** [comment]
@jpapillon @thednp 

I never posted a commit so I thought the "dist" folder from the master branche would be updated immediately after merging a PR.

I downloaded the "bootstrap-native-v4.js" from the "dist" folder of the forked version but still got the same issue, probably this one also needs to update the "dist" folder in order to work.

**Comment by jpapillon** [comment]
Hi @Vuurvlieg @thednp, when I made the changes, I forgot to run the build scripts. I created a new [pull request](https://github.com/thednp/bootstrap.native/pull/190) to update those.

**Comment by Vuurvlieg** [comment]
Latest PR is working fine, thanks!

**Pull request merged**
