### PR TITLE
Automate minification

### PR DESCRIPTION
**Pull request by RyanZim**
@thednp How's this?

I removed gulp since it is no longer needed.

The new minification tool minifies slightly differently than the old one (though file-size is similar), so this PR includes updates to the minified files.

To automatically minify, run `npm run min` from the project directory (or any subdirectory). The script takes about 1.3 seconds on my machine, so this should speed things up greatly.

### CODE REVIEW

**Comment by thednp** [comment]
Thank you. I hope you triple checked everything. I hope no gulp user will complain.

**Comment by thednp** [comment]
What do you think about [this](https://github.com/thednp/kute.js/blob/master/build.js)?

**Comment by RyanZim** [comment]
LGTM

**Comment by thednp** [comment]
I tested both files in my console and I get `4 verbose stack Error: missing script: min`. Ideas?

**Comment by RyanZim** [comment]
@thednp You need to copy https://github.com/thednp/bootstrap.native/blob/master/package.json#L8 to the `scripts` section of the package.json.

**Comment by thednp** [comment]
And then publish to npm again?

**Comment by RyanZim** [comment]
No need to re-publish IMO; the `main` field references the unminified files (just like it should).

**Comment by thednp** [comment]
Wait a minute, when does this happen, when should I `npm run min` ?

**Comment by RyanZim** [comment]
Either every time you make a change to the code (preferable IMO), or before each release.

**Comment by thednp** [comment]
ok now I get a different error. I think I should `npm install` each

```
var fs = require('fs');
var path = require('path');
var uglify = require('uglify-js');
```

Correct?

**Comment by thednp** [comment]
Indeed.

**Comment by RyanZim** [comment]
@thednp No need to manually install each one, they're in the package.json, just run `npm install` (or `npm i`, that's an alias).

BTW, `fs` and `path` are core node.js modules, no need to install them.

**Comment by thednp** [comment]
What about `uglify-js`?

**Comment by RyanZim** [comment]
That's in the package.json, just run `npm i` and the correct version will be automatically installed.

**Pull request merged**
