### PR TITLE
Handle transitionend emulation

### PR DESCRIPTION
**Pull request by nlemoine**
Hi @thednp 

This PR fixes some issues with the transition end emulation:
- if transition end isn't supported by the browser, the handler was executed right away. It now properly emulates a transition end and keeps the transition effect.
- when a transitioned element is hidden (`display:none;` for example), transition end event is never emitted. Therefore, the transitioned element get stuck in transitioning step (`class="collapse collapsing height="0px"` for a collapse component). It now handles this use case by checking if the callback was called (behavior borrowed from official BS).

I also added a quick fix on the `watch` script in your `package.json` that wasn't watching files and was only building v3.

Let me know if some changes are required.

### CODE REVIEW

**Comment by nlemoine** [comment]
Thanks for considering this PR!

**Comment by thednp** [comment]
@nlemoine please test the latest Master and let me know how it goes. I changed your code a bit to make it more inline with the project's standards and more consistent.

**Comment by nlemoine** [comment]
HI @thednp 

The code does not completely reflect the changes I made. It's missing an important part of this PR: 
```javascript
emulateTransitionEnd = function(element,handler){
    var called = false;
    if (supportTransitions) {
      one(element, transitionEndEvent, function(e){
        handler(e);
      });
    }
    setTimeout(function() {
      if (!supportTransitions || !called) {
        handler();
      }
    }, getTransitionDurationFromElement(element));
}
```
The `called` variable is used to check if the handler has been called in case transition end event isn't emitted (see the second bullet of my first comment).

But I just realized I forgot to set it to true once on transition end (or fake transition end). 

The commit following this comment fixes this.

**Comment by thednp** [comment]
Yes, I know, I will review and come up with a new code that takes your suggestions into consideration, please wait a bit, I found something inconsistent with the **Carousel** component and the `transitionend` handling.

**Pull request merged**
