### PR TITLE
Add webpack loader support

### PR DESCRIPTION
**Pull request by jonathanfleckenstein**
Moved the build logic into modules so that it can be called without the CLI interface. Moved helpers to there own module as they were the same in build and build-v4. Published an accompanying webpack loader to make integrating custom builds into webpack easier. I've tested the existing build process and it seems to build fine. Also, existing custom builds through the CLI still work as expected.

### CODE REVIEW

**Comment by thednp** [comment]
Thanks, I'll check this asap ofc ;)

**Comment by binarious** [comment]
Can you create a tag? I tried the webpack loader, because it's promoted in the readme. Without this PR released it doesn't work though.

**Comment by jonathanfleckenstein** [comment]
I’ve updated the loader readme to reference the merge commit on GitHub.
You can test by running

yarn add https://github.com/thednp/bootstrap.native.git#641148791eb03a68014b0b9857530a5a91299e56

On Feb 2, 2018, at 11:52 AM, binarious <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you create a tag? I tried the webpack loader, because it's promoted in the readme. Without this PR released it doesn't work though.

**Comment by jonathanfleckenstein** [comment]
Once the change makes it NPM I'll update the docs to `yarn add bootstrap.native@2.0.22`

**Comment by binarious** [comment]
@jonathanfleckenstein Thank you. How would I use it? What does it export? How can I configure things like `new bsn.Carousel(carousel, { interval: 5000 });`?

**Comment by jonathanfleckenstein** [comment]
@binarious I just pushed a small fix, it should now export the proper object. You'll have to upgrade to version 1.0.6 of the loader `yarn add bootstrap.native-loader@1.0.6`. Sorry about that, we're just using the data-api and I didn't notice the botched export.

Something like this should work now:
`import bsn from 'bootstrap.native';
new bsn.Carousel(carousel, { interval: 5000 });`

**Comment by binarious** [comment]
@jonathanfleckenstein Thank you for the fast response. It does work now 🙂.

**Pull request merged**
