### PR TITLE
CommonJS/RequireJS compatibility, Bower/NPM

### PR DESCRIPTION
**Pull request by IngwiePhoenix**
- `bootstrap.native` can be `require()`'d now, and if loaded via a `<script ...>` tag, it just turns back to it's old behaviour. In an environment without `window` being defined, a factory function is returned. Otherwise, the actual plugin.
- When you `cd` into the folder, you can create minified versions using Gulp. The `dist/` folder contains the latest snapshot.
- Bower and NPM are now supported too. their respective `.json` files should be correct.

To use gulp:

```
$ cd bootstrap.native
$ npm install
$ npm run gulp
```

And this will create a new distribution from `lib/` into `dist/`.

### CODE REVIEW

**Comment by thednp** [comment]
Would you please test this all and also edit the README for usage with all these things as well :D

**Comment by thednp** [comment]
Hold your horses for a second. Please consider the following:

Example, `bower.json` should have the following changes:
* `"description": "Bootstrap 3's JavaScript re-implemented in vanilla JS! No jQuery required, at all.",` should be `"description": "Native Javascript for Bootstrap 3, the sweetest Javascript library without jQuery.",`
* `"keywords": [ "bootstrap.native", "bootstrap",  "vanilla.js"  ],` should include `native` so please make it `"keywords": [ "bootstrap.native", "bootstrap",  "vanilla.js", "native javascript"  ],`

Another thing I noticed, for instance `package.json` 
* `"homepage": "https://github.com/thednp/bootstrap.native#readme"` should be `"homepage": "https://thednp.github.io/bootstrap.native/"`

Thanks for your attention :)

**Comment by IngwiePhoenix** [comment]
Hey.

Sorry, I must've been getting a little over-excited. o-o;

I did all the tests locally - from Gulp, to the dist, to the RequireJS and such, all the way up. I wanted to make sure that the PR is complete. :)

I'll fix the Readme and `*.json`'s in a little. The changes should automatically appear on this PR too sicne it'll go into master. That also means I'll revert README back to the original.

Once I commited that, I'll let you know!

Kind regards, Ingwie

PS: You are very welcome!

**Comment by IngwiePhoenix** [comment]
oH i just noticed that I had a misunderstanding in the part of the readme. I'll add that in. In fact, I actually put it into `index.js` as a doc-comment... Derp! :)

**Comment by thednp** [comment]
Please check my updates to the above comment. :)

**Comment by IngwiePhoenix** [comment]
I kinda did the doc-comment out of habbit. x) I'll fix that up for sure.

Abut the `*.min.js` files. I moved them into dist, because minified files usually are distributables, while the original JS files within lib/ are, well, the actual code. It just makes a bit more sense, since the minified versions are what is distributed to the client (= dist). Besides that, the Gulp task I wrote takes all the JS files from the lib folder and minifies them - i thought that'd be a distribution step.

However, if you prefer, I can change that behaviour to write `bootstrap-native.min.js` (currently `bootstrap.native.min.js` because I hit the dot instead of the dash) and its unminified friend to `dist/` as before, but writing all the other minified files back into `lib/min/`. That decision is up to you. I'll wait on your word on this one before I do any change there.

**Comment by thednp** [comment]
The file naming must remain the same for `/dist` folder(s), it's about CDN, I'm not 100% sure about it, I just wanna make sure everything is perfect before anything, anytime and everyone.

**Comment by IngwiePhoenix** [comment]
Here you are! :) Pushed my changes as requested.

- Changed the README to properly introduce the CommonJS/RequireJS usage and made extense notice about the factory functions. In fact, this method for changing the key values comes from jQuery itself.
- Updated the `*.json` files for NPM and Bower correctly with the description, keywords and alike. I just need to make the registries aware of the change in the files...but that is no biggie.
- I did keep the doc-comment in `all.js` on the root level. If you want that remove, I can do that too or you can remove it after merging.
- Gulp now writes the minified library files back into `lib/min/` as the current upstream has, while properly dropping `bootstrap-native(.min).js` into `dist/`.

I also have a 0.9.7 tag on my local repo, but I have a feeling that this isn't popping up in the PR...

**Comment by thednp** [comment]
Thank you, I'll check your repo and post here any comments.

**Comment by thednp** [comment]
I want you to know, I have no problem having your name in the files, just that adding all people's name in the file would create a huge list overtime. Makes sense to have a list of contributors in the README, or a simple link to repository contributors :)

**Comment by IngwiePhoenix** [comment]
Gotcha. :) Just wasn't sure about a good aproach to leave a tiny trail ^^ Gonna add that in.

**Comment by thednp** [comment]
No need to be sad about my decision on naming, I think it's fair for all.

**Comment by thednp** [comment]
Would this stuff require work with CDN files as well? Does it have an `on(error)` handling? Sometimes files don't load. If so, it would be great to be able to fallback to local distribution.

**Comment by IngwiePhoenix** [comment]
It does automatically fall back. Take a look into the files themselves. If `module` is not defined at all, it'll return to what your original implementation was entirely.

Besides, the `on("error")` event should be given by the module system in question. Though, there should be no problem. I did not run across any in my testing.

**Comment by thednp** [comment]
Please add YOUR name to all your files, example below

<pre>
// Bootstrap Native Javascript
// Bower/npm/Require implementation by Your Name

</pre>

**Comment by IngwiePhoenix** [comment]
Ohh, I get it. I only added "Edited by". Let me fix that into a proper line.

**Comment by IngwiePhoenix** [comment]
Now it reads:

```
// Native Javascript for Bootstrap 3 | Affix
// by dnp_theme
// Bower/NPM/Require implementation by: Ingwie Phoenix
```

That this one look right?

**Comment by thednp** [comment]
It's alright my friend, just your name should be in your own files only.

**Comment by IngwiePhoenix** [comment]
Well I did modify every file in `lib/`. So... should I add my name in them too? I did that on my local copy for the moment.

**Comment by thednp** [comment]
All YOUR files should have YOUR name credits (if you include me, it's ok, but not required), my files keep my name only.

**Comment by IngwiePhoenix** [comment]
Alright, got it. Will push the commit in a sec.

**Comment by thednp** [comment]
No rush, take your time, test everything twice.

**Comment by thednp** [comment]
If you care to put your name on it, I will let you know a much better way.

**Comment by IngwiePhoenix** [comment]
Oh it's fine. :) There you are. The code is ready to merge. If you have anything else on your mind, let me know.

**Comment by thednp** [comment]
OK now, last thing: please consider editing the html files, write a new section in the `Use` chapter, about using your stuff, later I will write a big thanks in your name, and this is gonna be visible in the demo and download pack.

**Comment by IngwiePhoenix** [comment]
I will! I am just going to do a last confirmation, and give out the HTML fix. I also spotted a little issue in my exporting function. Those, however, are fixed in less than a minute.

You are very welcome! I'll be happy to use this in my project - and it is going to help me a lot!

**Comment by thednp** [comment]
Alright, let me know when this is all tested, can you please provide some screenshots? I need to know this works perfect before I push a new version to the CDN.

**Comment by thednp** [comment]
You can check my new project README :)

**Comment by thednp** [comment]
Alright, I've made some changes to your files, checking everything, and waiting for your fix.

**Pull request merged**
