### PR TITLE
Refactoring: Deleted double querySelector using; replaced regexps to s…

### PR DESCRIPTION
**Pull request by nicola-spb**
Hi,
Refactoring: Deleted double querySelector using; replaced regexps to slice(-1), 'click' and 'focus' and chartAt(0); moved extra condition (firstChar === '.' or  firstChar === '#') from cycle; replaced all targetsReg

Please, regenerate dist js files

### CODE REVIEW

**Comment by thednp** [comment]
@What's up with the RegEx? What is the reason to be replaced with `slice` and `charAt(0)`?

**Comment by nicola-spb** [comment]
You can compare performance of your regexp, slice(-1) and chart(0). Performance different in some times. I tested in chrome.

Smaller size it's not important. When you use .min.js file it's less 1 kb but when you execute your script in mobile browser then you will see proccesor it's importnat.

Now when I open your demo site on android 4.2 and 2 cores then browser load page but after I have 5-10 s waiting for script execution. Thats why I wanna change it before use it in production.

**Comment by thednp** [comment]
I agree with you. However, I am going to do some improvements over your changes, here's an example:
`/\#$/.test(anchor.href)` is not the same with `anchor.href.slice(-1) === '#'`, in my case it checks whether the HREF value is just `#`, in that case we will `preventDefault` or if it's something like `#some-id` we will actually not do `preventDefault`.

Also I don't see why my code isn't perfect in the case of popover and tooltip [container](https://github.com/thednp/bootstrap.native/pull/173/commits/1140dd360ca33438e80524d2f1ec7b57c046698b#diff-379ea81f52bc2c35219ab9a46225d262).

**Comment by nicola-spb** [comment]
slice(-1) get last symbol of string and after we compare it. Your regexp do the same. I don't undestand. Can you give example with different results?

In popoover 1) I deleted twice execution of querySelector. if first querySelector is true then we execute it again. I cached value and querySelector execute one time for one selector. 2) And replaced regexp with click and focus. In this regexp compare full word.

**Comment by thednp** [comment]
> slice(-1) get last symbol of string and after we compare it. Your regexp do the same. I don't undestand. Can you give example with different results?
Oh, I didn't know we could do that with `slice` :) Cool!

About that, I understand what you mean, I will make proper edits asap.

Thanks again, excellent suggestions.

**Comment by nicola-spb** [comment]
queryElement(options[container]) ? queryElement(options[container]) 
-                  : ......

2 times execute queryElement.

P.s. my mistake in prev comment: querySelector is queryElement

**Comment by nicola-spb** [comment]
I dont know about how it make faster bootstrap-native. I think it make be better and when I found it then I wanna fix it.

I think we can improve performance of closestElement if it will find some elements by some selectors in one walk of tree. I saw you execute it some times for one element but use different selector. 

It should be better!

**Comment by thednp** [comment]
>I think we can improve performance of closestElement if it will find some elements by some selectors in one walk of tree. I saw you execute it some times for one element but use different selector.

So you like the way I changed the utility in the latest master I guess.

Yeah, some of the code is almost 3 years old now, with very little knowledge (at that time) as a basis. But it's good we learn and improve stuff over time.

**Comment by nicola-spb** [comment]
Thank you!

**Comment by thednp** [comment]
Hey, [some users](https://github.com/thednp/bootstrap.native/pull/161/commits/f3ff4748bf86d487e510656b5ee183d0dd0b2f74) proposed this `if ( !titleString || titleString == "" ) return;` check.

**Comment by nicola-spb** [comment]
Hi,

!titleString include condition titleString == ""

**Comment by nicola-spb** [comment]
You are right. Don`t change it. 

`!titleString || titleString == ""`

If I have 
`new String('')`
My condition will incorrect.

Other in this commit I think is correct.

**Comment by thednp** [comment]
@nicola-spb I applied all your latest changes.

I am now developing a new feature to allow the library to be used in the `<head>` without any additional initialization script, and exposing some library information and useful methods. Interested in testing that?

**Comment by thednp** [comment]
OK Now you can test the latest master.

**Comment by nicola-spb** [comment]
Ok. Thank you. I`ll test it.

**Pull request closed without merging**
