### PR TITLE
(Feat) Added the destroy method to Tooltip V4. Added removeAttribute …

### PR DESCRIPTION
**Pull request by cvaize**
Added the destroy method to Tooltip V4. Added removeAttribute method to utils V4.

### CODE REVIEW

**Comment by cvaize** [comment]
I want to extend the capabilities of this library without increasing its weight. Look at the V4 Tooltip method I added.destroy. I considered the possibility of re-initialization. Test this code, and give your opinion. Can I maintain this library with you?

**Comment by thednp** [comment]
I'm happy you've spent time to develop this method for tooltip as well as for your interest in contributing further. 

This feature has been a request from many people, I believe this will come even more handy when we  move to ES6/ES7 standard. There are only 2 things I would change to your code:

* make a singe `toggleEvents(change)()` to work for both `bind` and `unbind`
* `if ( element[stringTooltip] )` check before adding the events on initialization is good to make sure we don't re-bind the events every time, some folks are still used to `jQuery(elem).do` shenanigans

Will talk to you later ;)

**Comment by cvaize** [comment]
Didn't understand 2nd paragraph. You mean re-initialization? The destroy method is called before initialization, otherwise method references are lost.
image

**Comment by cvaize** [comment]
Changed destroy to unbind. I think I understand =)

**Comment by cvaize** [comment]
I will be glad to cooperation, I will do the following #303 . If you want to communicate in person, here is my email cvaize@gmail.com

**Comment by thednp** [comment]
`this` is already bound to `self`, while `element` is your `elem`, so your function will look like this:

```js
      toggleEvents = function(action){
        action(element, mouseHover[0], self.show);
        action(element, mouseHover[1], self.hide);
      };
```

**Comment by cvaize** [comment]
About `element` fully agree. But at the expense of `self` I do not agree. In the line `var self = this` you assign a reference to a new function object to the variable, in consequence of which `self !== this[oldTooltip].`

image

image

**Comment by cvaize** [comment]
Your code will not work because function references will not match when you delete a listener, which means that listeners will not be deleted. I ran tests.

**Comment by thednp** [comment]
There is something else in the way. Instead of `( element[stringTooltip] )` it should be `( !element[stringTooltip] )`, the point being that we don't want to re-bind events to element on every `new Tooltip(element)`.

I will have a look at this as soon as I can. Promised.

**Comment by cvaize** [comment]
By creating a new `Tooltip` object, we cannot avoid rebinding listeners, otherwise we lose references to methods from the previous `Tooltip` object, which means that we cannot delete listeners of these methods. I'm building on my extensive experience with JS context. We have a solution that in my opinion is heavier with the current architecture, we can overwrite the fields and methods of the "Tooltip". But this will significantly increase the amount of code and may not give a performance boost. Since you will have to overwrite the variables in the old functions. In my opinion it is better to leave as is. Rewriting listeners is less expensive in terms of the amount of code.
image
I will be glad to know your opinion and solution of this issue.

**Comment by cvaize** [comment]
My solution will slightly increase the amount of code, but will update the parameters without re-creating the Tooltip and without re-binding the event. Viewed in this way, it's a good solution. Should I implement it for clarity or do you have a more elegant solution?

**Comment by cvaize** [comment]
Here is my solution without re binding listeners

**Comment by thednp** [comment]
@cvaize I wanna thank you for researching ways to improve the components; as you can see the code from previous versions, we're trying to avoid re-binding event handlers on every `new ComponentName(target)` instance using `if ( !element[stringTooltip] ) { bindEvents }`.

Also we're making sure we're not "polluting" the `window` / `document` with event handlers for every component and it's specific functionality; the events are bound for instance for `window` resize and the Tooltip component ONLY when the tip is shown so that we can trigger `self.hide()` if necessary (because we don't use Popper.js) and then resize is unbound after the tip have been hidden.

What I'm trying to say is that we may NOT need to do use `this[listenerShow]`, a more simple solution I've seen in other libraries:

```js
// a bind works best, here's one of the tricks I've learned
var self = this = stringTooltip.prototype;
```

Then on init we can do the following:
```js
// bind events only if they're not
if ( !element[stringTooltip] ) {
  toggleEvents(on);
}
// re-link the bind, remind the memory controllers who's THIS
element[stringTooltip] = self;
```

Another problem is the `options` object. For security reasons, in the original design I came up with the idea to brake this object into multiple variables inside the component instead of working with `self.options = options` (extend). 

This makes the initialization -> destroy -> re-initialization a very hard task to do (even impossible in some cases) because the links between the options object and `THIS` is completely arbitrary, sometimes even broken. The issue of options object is something very important to consider in redesigning components for ES6/ES7 coding standard.

**Comment by cvaize** [comment]
I tested the `var self = element[stringTooltip] || this;` solution. I expected to face the problem of immutability of parameters in already written functions, as well as when using the construction `var component = new ComponentName( target); component.show(); component = new ComponentName (target); component.hide ();` there are bugs, because we return a new component, and work with the old one. Could you show the solution without `listenerShow`?

**Comment by cvaize** [comment]
image
image

**Comment by cvaize** [comment]
My solution based on `listenerShow and listenerHide` kept unchanged only the `listenerShow and listenerHide` methods that used the `Tooltip` from the element, which means that when used always at the new initialization returned a full component, with all parameters, a reference to which was stored in the element. I long to see your decision =)

**Comment by thednp** [comment]
Hello and Merry Christmas :)

I'm playing with your code and I have some notes:

* I see no need for the `listenerShow` and `listenerHide`, I'm working on an easier way to fix this once and for all, should be useful for all components, but I believe I already have an idea
* the `template` option must be NULL by default and should be used ONLY via JavaScript initialization, similar to our Popover implementation (a component I'm gonna play with); the point is that `data-template="<div class="tooltip"></div>"` can result in something like layout breaks or other issues
* I found some opportunities to simplify the code a bit
* keep in mind that future versions will not use manual string tokens to ease with the ES6/ES7 transition
* also for future versions I'm considering transforming the initialization object to store the options object in `this.options` object instead of `this` to simplify things

Keep an eye on the master branch in the next couple days for new fixes and improvements as suggested in your fork. Cheers

**Comment by thednp** [comment]
@cvaize please test latest master and let me know how it works ;)

**Comment by cvaize** [comment]
@thednp Surfaced the same bugs that I bypassed methods "listenerShow"

**Comment by cvaize** [comment]
The reason for this is that the new object when reinitialized does not contain the necessary fields in this approach. Always when reinitializing, a new, configured object must be created. But the listener functions of the old object must be preserved to remove listeners from the element.

**Comment by cvaize** [comment]
We can compromise by renaming the "listenerShow" methods and placing them in a hidden place to exclude them from the object interface, the only correct place to put them with this approach is the element itself. I suggest creating a hidden section in the element and putting them there. For example: "element.privateTooltipSettings = {"listenerShow":fun(){}, "listenerHide":fun(){}}

**Pull request closed without merging**
