### PR TITLE
Fix error on tab-native when there is no dropdown tab

### PR DESCRIPTION
**Pull request by McRipper**

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
There was another PR like that the other day, wasnt there?

**Comment by thednp** [comment]
@McRipper look at the code careful, there is already a merge of the `if (self.dropdown) {}` change mat.

**Comment by McRipper** [comment]
Sorry, I didn't saw it was already fixed in main branch

**Comment by thednp** [comment]
It's ok Em, thanks for the heads up.

**Pull request closed without merging**
