### PR TITLE
Added addition to Use section, JS hotfix

### PR DESCRIPTION
**Pull request by IngwiePhoenix**
There you are!

I merged your upstream back into my fork and fixed the very little and lastly remaining errors, and added the use section. I can spot no further work to do for now. :)

Don't worry about the amount of noise in this PR, its mainly due to me having re-run Gulp to write the fixed JS files as minified files also.

Congrats, your package is now fully working with either NodeJS, the browser and/or a module loader! :)

### CODE REVIEW

**Comment by thednp** [comment]
I would suggest changing the trunk index.html (not gh-pages) to demonstrate the require/npm fallback with CDN and local repo.

**Comment by IngwiePhoenix** [comment]
Okay. Will do that! I didn't take notice of the `gh-pages` branch untill now. o.o'

**Comment by thednp** [comment]
No problem, I will update that one accordingly.

**Comment by IngwiePhoenix** [comment]
While writing two tests to showcase NodeJS and Browser usage, I found a little issue with the exporting function. You may want to merge this.

When I have a bit more time, I'll write actual test cases to verify changes better. Now, to update gh-pages. And, i'd suggest merging  these commits to patch the little issue i found. :)

**Comment by IngwiePhoenix** [comment]
All done, all confirmed

... all exhausted. Phew! :)

I think my task is done now, if nothing else arises. All that is left is for you to merge my fork's mnaster and gh-pages. and that should be it.

**Pull request merged**
