### PR TITLE
implement getInstance and getOrCreateInstance

### PR DESCRIPTION
**Pull request by lekoala**
Fixes https://github.com/thednp/bootstrap.native/issues/431

### CODE REVIEW

**Comment by thednp** [comment]
Thanks for the commit. I was about to say that `static` methods don't work with buble compiler, but since our V5 doesn't use it, might make more sense. However I would prefer to assign these static methods to the base component similar to how components have their static methods.

I believe there could be many people who might compile the BSN V5 to ES5 and this would be a breaking change all of a sudden, unless they use Babel which DOES support many of the new experimental ES6+ features.

**Comment by lekoala** [comment]
Agreed, i was lazy and simply copy pasted code from bs5. here i've updated to add only getOrCreate static method using object assign

**Comment by thednp** [comment]
Have you seen [this](https://github.com/thednp/bootstrap.native/issues/431#issuecomment-1044243574)?

**Comment by lekoala** [comment]
@thednp ;-) i did after making the update. good learning experience anyway to see how it's done.
it's up to you, it's there. if you think it's worth adding it
otherwise, i will indeed use the getInstance || new pattern instead

**Comment by thednp** [comment]
Let's close this for now.

**Pull request closed without merging**
