### PR TITLE
Fixed getOuterHeight

### PR DESCRIPTION
**Pull request by janpanschab**
Ommited var in collapse - getOuterHeight.

### CODE REVIEW

**Comment by thednp** [comment]
do you get any error or miss-behave because of this omission?

**Comment by janpanschab** [comment]
Yes, error message: Uncaught ReferenceError: getOuterHeight is not defined.
Looks to me, the "var" is missing only.
I am using browserify (if it helps).

**Comment by thednp** [comment]
Ok, please pull all the little issues you can find (I don't use and have no idea how to use browserify), then I'll merge and get a new release.

**Comment by thednp** [comment]
@janpanschab are you getting other error or found any issue? Please reply, I will tag release a new release once you reply.

**Comment by janpanschab** [comment]
Everything is OK for now. `collapse-native.js` is the only one script which I have implement. 
BTW thanks for the project!

**Comment by thednp** [comment]
Alright, I'll do the new release asap. Thanks

**Pull request merged**
