### PR TITLE
introduce rollup bundler

### PR DESCRIPTION
**Pull request by midzer**
Hi again,

here's a setup to bundle bsn with rollup. Babel with preset-env is used to transpile JS. I've tested dist JS files only for Drowndown functionality until now.

The next days I'm going to import individual components in a project to see how this works out.

Cheers
midzer

### CODE REVIEW

**Comment by thednp** [comment]
Thanks so much for your contribution, amazing work :)

**Comment by midzer** [comment]
Thanks. Been great fun. I had a (hopefully good) sample `rollup.config.js` at hand ;)

I am thinking about moving `src` folder and containing `index.js` to root as well.
This way, you should be able to just do
```
import BSN from 'bootstrap.native'
```
and import individual components via
```
import Alert from 'bootstrap.native/src/alert-native.js'
```

What do you think about that?

**Comment by thednp** [comment]
Don't worry about those, you took the thoughts out of my mind. I have some other questions:

* Is the `_classCallCheck` required for the ES5 build to work, can we just remove it somehow? Perhaps we could do for instance `function Alert(element){}` instead of `constructor(element){}`?
* Is it possible to export components to window on the ES5 build? We don't want to upset people that might have to change `new Tooltip(element)` to `new BSN.Tooltip(element)`.
* Just like the above, is it possible to expose `initCallback()` and `removeCallback()` to `window.BSN` folder, just like in our previous builds?
* Can we have an optional build option for included components `[alert,button]` similar to the previous build script?
* Can we order required utils to functions first then vars?
* Can we set a custom text indentation for the build, the way babel works is kinda sloppy? Or is anything we can do about it?
* Similar to original plugins, can we also do an `esm` build? Can we also do a bundle to include polyfills (those will need to be lebabified)?

If I have other questions, don't miss them :)

**Comment by thednp** [comment]
To answer my own question, I found that `export default function Alert(element){}` seems to do the job. What do you think about that?

**Comment by thednp** [comment]
I think I figured on how to do ESM as well.

**Comment by midzer** [comment]
Tough and good questions! As I'm just learning rollup myself, I have to investigate more deeply.

A checklist in https://github.com/thednp/bootstrap.native/issues/306 would be helpful what tasks are still to be done and others might help out as well.

Meanwhile, until you push your new findings, I'm going to look for other libraries which do rollup and esm modules, too.

Sorry of being of no help right now. Let's solve remaining aspects together.

**Comment by thednp** [comment]
@midzer will do asap

**Pull request merged**
