### PR TITLE
Fix slide and slid event mixup

### PR DESCRIPTION
**Pull request by RyanZim**
Follow-up for #74.

@thednp I'll be waiting for your release; don't forget to publish to npm.

### CODE REVIEW

**Comment by RyanZim** [comment]
BTW, not sure if this should be a patch or major release. If people are relying on the old behavior, you could get some people pretty upset if you publish it as a patch release. The docs did accurately document the old behavior, though it was incorrect as per jQuery bootstrap. The decision is up to you.

**Comment by thednp** [comment]
We'll see about that.

**Comment by thednp** [comment]
> @thednp I'll be waiting for your release; don't forget to publish to npm.
Check npm now.

**Comment by RyanZim** [comment]
LGTM

**Comment by thednp** [comment]
Alright, thank you for the PR. How about the auto-minimize script?

**Comment by RyanZim** [comment]
I'll try to get to it soon, I've been extra busy of late and haven't had much time for open source.

**Comment by dgt41** [comment]
@RyanZim @thednp this broke the demo site (or the demo is not updated?)

**Comment by RyanZim** [comment]
Oops, seems you were using the events in your header @thednp. I wasn't aware of that.

**Comment by thednp** [comment]
I will fix it in a sec. See my reply in the open issue.

**Comment by RyanZim** [comment]
Your fix LGTM

**Pull request merged**
