### PR TITLE
(Fix) Incorrect operation of Tooltip and Popover with focus events on mobile devices, in particular Iphone 5 https://github.com/thednp/bootstrap.native/issues/345

### PR DESCRIPTION
**Pull request by cvaize**

### CODE REVIEW

**Comment by hoektoe** [comment]
Is the NPM package update with this fix? See npm package last updated 6months ago. Just unsure how I can get this version.

**Comment by thednp** [comment]
@hoektoe haven't had the time to finish the documentation yet to publish V4 es6, the new version to npm yet, but untill then you can always install from girhub

https://docs.npmjs.com/cli/install

**Comment by hoektoe** [comment]
Awesome thanks didn't know can do it this way. Thanks for quick reply and your work on the repo. Anything you need help with?

**Comment by thednp** [comment]
A good plan to write a consistent documentation.

**Comment by hoektoe** [comment]
Sorry to keep bothering about this.

`npm install https://github.com/thednp/bootstrap.native.git`

Getting on build:
`ERROR in ../node_modules/bootstrap.native/dist/bootstrap-native.esm.js
Module build failed (from ../node_modules/bootstrap.native-loader/index.js):
Error: Cannot find module 'bootstrap.native/lib/build-module.js'`


What do you not like about v3 documentation?

**Comment by thednp** [comment]
We're working with rollup and es6 code, that wii part is out of date and the webpack loader isn't updated.

**Comment by thednp** [comment]
Still why bother with webpack when you have rollup setup done and ready to use?

**Comment by thednp** [comment]
@cvaize is this fix still required in 2022?

**Pull request merged**
