### PR TITLE
V3: in someEl.Tab.show(), next was undefined

### PR DESCRIPTION
**Pull request by rloth**
Hello !
When I tried to used the show() from tab-native, it complained that next was undefined, so here is my fix for you to consider.
Thanks for the general work on bootstrap-native it's a very useful project for me.
RL

### CODE REVIEW

**Comment by thednp** [comment]
I cannot confirm the issue, do you perhaps have a test page?

**Comment by rloth** [comment]
For me it came up by trying the stock example from https://thednp.github.io/bootstrap.native/#componentTab but perhaps it's affected by other vars in the page... I'll see if I can reproduce it on a page with only this and keep you posted after my office hours.

**Comment by thednp** [comment]
I think I know why this could potentially happen. First, `next` is defined with the `clickHandler`, but if you use the `show()` method via JavaScript, it's not going to be defined. I will make proper fixes asap.

Thanks for the report.

**Comment by thednp** [comment]
Please test the latest master and let me know how it works.

**Comment by rloth** [comment]
Yes indeed it was direct js use so next was undefined.
Now `next = next | element` does fix it ! (tested with your latest V3...)
thanks for the quick action :)

**Pull request closed without merging**
