### PR TITLE
Custom Bundle Script

### LINKED ISSUE #71: Simplify prototypes for faster execution and simplify bootstrap.native.js packaging
I have a new working code for all modules to work a bit faster, it's a bit more simple and I am also considering packing the `bootstrap.native.js` file different and not just a concatenation of the modules.

The reason is simple: why write same utility function over and over (`addClass` or `isIE`) as well as using module definition for each module when in fact an user gets the all in one package to use it on his web pages, without the need to do require, import, etc.

I really need to know what people think about it.

### PR DESCRIPTION
**Pull request by RyanZim**
Closes #71.

@thednp I also added a watch script, `npm run watch`. This will watch for changes to the files in `lib/` and rerun `npm run build` for each change (Very handy for development).

I also changed the script tag in index.html to reference the minified bundle (`dist/bootstrap-native.min.js`) instead of `dist/bootstrap-native.js`.

Let me know if anything else needs changed.

### CODE REVIEW

**Comment by RyanZim** [comment]
Thanks!

**Comment by thednp** [comment]
Hey @RyanZim, I'm a little concerned about performance with these IIFE and the new code for Tooltip and Popover. IIFE always sets a new scope generally and as a result, performance is most likely traded.

I have an idea: I can set a custom variable for each script DATA API to hold the count of each instance, EG:

```
for ( var m = 0, mdl = Modals.length; m<mdl; m++ ) {
  var modal = Modals[m], options = {};
  // do the dew
}
```

What do you think?

**Comment by thednp** [comment]
UPDATE: @RyanZim please update from master and make a test. Tell me what you think.

**Comment by RyanZim** [comment]
@thednp Looking over your commit, I think the code will work.

My only concern is that you (or another contributer) will someday not think about the identifiers that are declared outside the file and will cause a collision. If you're willing to take that risk (and are sure it won't happen), go for it! It's just a risk I personally wouldn't take.

**Comment by thednp** [comment]
Thanks @RyanZim, I will go ahead and write some stuff into build.js about this.

**Comment by RyanZim** [comment]
@thednp While you're at it, you might want to make a `CONTRIBUTING.md` that includes this info.

**Comment by thednp** [comment]
That's a cool idea. I will leave a special section for you regarding NPM/node.js.

**Pull request merged**
