### PR TITLE
Dropdown now working properly on beta

### PR DESCRIPTION
**Pull request by ctl**

### CODE REVIEW

**Comment by thednp** [comment]
Will this commit also work with nested dropdown menus?

**Comment by ctl** [comment]
@thednp what you mean under nested dropdown menus? I didn't found that in docs

**Comment by ctl** [comment]
There is no nested dropdown menus in beta

**Comment by thednp** [comment]
Look at the second example in the right [here](http://thednp.github.io/bootstrap.native/#dropdownExamples).

**Comment by ctl** [comment]
But it's works

**Comment by thednp** [comment]
Try your code with this sample code

```
<div class="dropdown">
  <a id="drop2" href="#" class="dropdown-toggle" data-toggle="dropdown" data-trigger="mouseover" aria-haspopup="true" role="button" aria-expanded="false">Nested <span class="caret"></span></a>
  <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="drop2" tabindex="0" aria-expanded="true">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Another action</a></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Something else here</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation" class="dropdown">
      <a role="menuitem" tabindex="-1" href="#" data-toggle="dropdown">Sub-menu <span class="caret"></span></a>
      <ul class="dropdown-menu left" role="menu" aria-labelledby="drop3" tabindex="0" aria-expanded="false">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Level 1</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Nested Menu</a></li>
        <li role="presentation" class="dropdown">
          <a role="menuitem" tabindex="-1" href="#" data-toggle="dropdown">Other stuff <span class="caret"></span></a>
          <ul class="dropdown-menu left" role="menu" aria-labelledby="drop4" tabindex="0" aria-expanded="false">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Level 2</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Nested Menu</a></li>
            <li role="presentation" class="dropdown">
              <a role="menuitem" tabindex="-1" href="#" data-toggle="dropdown">Even more stuff <span class="caret"></span></a>
              <ul class="dropdown-menu left" role="menu" aria-labelledby="drop4" tabindex="0">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Level 3</a></li>
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Nested Menu</a></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </li>
  </ul>
</div>
```

**Comment by ctl** [comment]
image

**Comment by thednp** [comment]
OK let's take it this way, show me an example where my code doesn't work.

**Comment by ctl** [comment]
@thednp what do you mean?

**Comment by thednp** [comment]
I mean a page example where the code is faulty.

**Comment by ctl** [comment]
Why you closed this????

**Comment by ctl** [comment]
https://jsfiddle.net/u9jwcpx5/1/

**Comment by thednp** [comment]
It's all good to me

https://codepen.io/thednp/project/editor/DyyBEV/#0

**Comment by thednp** [comment]
@ctl have you found anything else with V4?

**Comment by ctl** [comment]
@thednp , no. Possibly everything else is working.

**Comment by thednp** [comment]
@ctl your issue is fixed now, however, it's a bit different than your commit, so I will let you know asap.

**Comment by thednp** [comment]
It seems I hav to update more than just the Dropdown, Popover and Tooltip are also out of date.

**Comment by thednp** [comment]
@ctl please download latest master and do some tests, changes here https://github.com/thednp/bootstrap.native/commit/80a187f2d0cd915bd40660e1506b7f44dd6eefc6

**Comment by thednp** [comment]
I need your confirmation before I push the update to the clouds and npm.

**Comment by ctl** [comment]
@thednp , Sorry for late response , but i wasn't at home . I'll try now

**Comment by ctl** [comment]
https://jsfiddle.net/bq7x9spr/

**Comment by ctl** [comment]
@thednp , it's works properly

**Comment by ctl** [comment]
I mean dropdowns , tooltips , popovers

**Comment by thednp** [comment]
Thanks, so we're safe to do a release perhaps, but I'm waiting for more people to get their hands on.

**Comment by thednp** [comment]
@ctl the latest version is now live on npm and soon to be available on the CDN clouds.

**Pull request closed without merging**
