### PR TITLE
Fix dismissal of dropdown by clicking svg with href

### PR DESCRIPTION
**Pull request by fmasa**
Fixes https://github.com/thednp/bootstrap.native/issues/351

Even though the original issue was closed, this bug is still present for both Bootstrap 4 and Bootstrap 5.

### CODE REVIEW

**Comment by thednp** [comment]
Hi @fmasa, I don't understand why you have to check if `element.href` is string when we mostly need to know if it's defined and isn't empty.

**Comment by fmasa** [comment]
The problem is when `element` is `<use>` in `<svg>`. In that case `element.href` is not a string, but instance of [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString) which does not have `slice` method.
image

**Comment by thednp** [comment]
Understood. Will review this asap.

**Comment by thednp** [comment]
I think `anchor.hasAttribute('href')` should be more consistent, wouldn't you agree?

**Comment by fmasa** [comment]
@thednp I agree. I updated the PR accordingly.

**Comment by thednp** [comment]
Sweet, will merge the PR as soon as I finish mine.

**Comment by thednp** [comment]
Please check latest master.

**Pull request merged**
