### PR TITLE
Fix modal button handler

### PR DESCRIPTION
**Pull request by nlemoine**
Hey there, 

I noticed a tiny issue with the modal button. Consider the following code:
```html
<button type="button" data-toggle="modal" data-target="#modal">
    <span class="random-icon"></span>
    LABEL
</button>
```
When clicking the icon, nothing happens. Because [here](https://github.com/thednp/bootstrap.native/blob/45013c9e21cb75f5474d1b42e493f243e21f181f/lib/V4/modal-native.js#L157), you get the event target. Which actually is the button as long as no HTML tag is in the button. But If you add, say an icon in your button and click happens on the icon, the [whole logic behind](https://github.com/thednp/bootstrap.native/blob/45013c9e21cb75f5474d1b42e493f243e21f181f/lib/V4/modal-native.js#L158-L159) won't work. 

So I just changed `e.target` to `this` which refers to the listened element, the `<button>`.

### CODE REVIEW

**Comment by thednp** [comment]
I will review this PR later because using `this` over `e.target` has some quirks with legacy browsers. Also I'm considering exporting all events to `Document` to handle later added elements easier than we currently are.

**Comment by Vuurvlieg** [comment]
I noticed this too. However, I used something like the following code to fix this, but your solution if way better ofcourse.

> if (ev.target.tagName.toLowerCase() == 'button')
{
	var element = ev.target;
}
else
{
	var element = ev.target.closest('button');
}

**Comment by thednp** [comment]
I'm closing this for now, this works for me, the very first demo clearly uses icon for the button, no problem there.

**Comment by thednp** [comment]
That's why we leave it for later.

**Pull request closed without merging**
