### PR TITLE
Set called to true once transition has ended

### PR DESCRIPTION
**Pull request by nlemoine**

### CODE REVIEW

**Comment by thednp** [comment]
I'm working on this right now, please wait for my code, it's gonna be out in a few minutes now.

**Comment by thednp** [comment]
So far Carousel, Tooltip, Popover components have been updated to work with the new handler. Some more tinkering needs to be done for Collapse and probably Tab as well.

**Comment by thednp** [comment]
Please test latest master. Thank you.

**Comment by thednp** [comment]
@nlemoine please test the latest code.

**Comment by nlemoine** [comment]
I ran some tests using the `v4.html` both with `supportTransitions` set to `true` and `false`.

Here are some results.

### `supportTransitions = false`

- **Carousel** 
  - bug: no transition emulated
  - reproduce: click on any handler (carousel indicators, arrows)

### `supportTransitions = true`

- **Modal**
  - bug: I think this is the same described in #204
  - reproduce: click on "launch modal demo" and type `esc` key twice fast (while modal is transitioning), then try to open modal again, it will appear and disappear immediately

### Whether `supportTransitions` is `true` or `false`

- **Collapse**
  - bug: when using the `parent` feature (accordion context), two groups can be opened
  - reproduce: close all collapsibles, click on "Collapsible Group Item #2" and quickly click on "Collapsible Group Item #1" (while "Collapsible Group Item #2" is transitioning), you'll get both groups opened.

I don't think they all are related to the changes brought to transition emulation.

I have an unrelated question regarding "code style" of BSN:
```js
var called = 0, duration = getTransitionDurationFromElement(element);
supportTransitions && one(element, transitionEndEvent, function(e){ handler(e); called = 1; });
setTimeout(function() { !called && handler(); }, duration);
```
Why trying to write as less code as possible? Your code is already going through an uglifier which does this job for you. IMHO, this makes code far less readable and makes it hard to adopt a well known coding standards (prettier, etc.).

**Comment by thednp** [comment]
Why messing with that? The `supportTransitions` is always `true` for modern browsers, it doesn't make sense to force the event callback immediately, long before the animation finishes. We're not going to fix what the browsers aren't meant to do IMO. I can confirm something feels messy but only with Edge/IE for which I don't intend to fix transitionEnd related issues.

On the other hand, V4 is meant for IE10+/Edge, both supporting transitions, but NOT supporting a ton of modern `Event` API, probably your test was conducted without a proper polyfil, not sure. BUT even with modern browsers the library isn't 100% bullet proof, just like the original plugins are, so keep that in mind. For that reason we might just ditch the entire `supportTransitions` related code, but we simply keep it to have it somewhat inline with V3 in the sense that it offers some support for IE9+.

As for the coding style, I know it sucks for readability, however it's far better than the previous versions, I think the 1.X series was terrible, so it's the best I can get to read an entire function body without scrolling too much to get the best overall picture.

**Comment by nlemoine** [comment]
> Why messing with that?

Because BSN includes `supportsTransitions` checks. Why keeping it if not properly supported? Like you, I think this could be removed. Depends if you what browsers you want to target. That's your call.

> probably your test was conducted without a proper polyfil, not sure

Tests I made have been done on latest Chrome. 

> BUT even with modern browsers the library isn't 100% bullet proof, just like the original plugins are

I think Modal and Collapse issues I mentioned could probably be fixed. I can't see them in official BS.

**Comment by thednp** [comment]
I've been tinkering with Modal and I think it should work a bit different, in terms of event handling. An private variable `isAnimating` will definitely prevent it from triggering dismissing handlers (via `Esc`, click on overlay). Which is something we use for Carousel and Tab. This method would also fix Collapse if we can find a way to actually make it work like that.

**Pull request closed without merging**
