### PR TITLE
Updated index.html with new use case for Bower and NPM

### PR DESCRIPTION
**Pull request by IngwiePhoenix**
What I did not update was the `bootstrap-native.min.js` link since I never used the delivr CDN. So I'll leave this edit to you. :)

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Also I just noticed I forgot to change the "main" entry in bower.json. You may want to fix that from

    bootstrap.native.min.js

To

    bootstrap-native.min.js

**Comment by thednp** [comment]
I fixed bower.json. I updated demo page with proper credits. I wish I had more testers to check the implementation before I push the next release to CDN.

Thanks a million for your hard work.

**Comment by thednp** [comment]
Quick question: https://www.npmjs.com/package/bootstrap.native

If this is your stuff there, please write a small description with link to github demo. I've given you so much work, I realize I was a pain, guilty, but I hope this would be the last one :)

Thanks so much.

**Comment by thednp** [comment]
I found this https://libraries.io/npm/bootstrap.native/0.9.7 please check repository link

`https://github.com/git+thednp/bootstrap.native`

should be 

`https://github.com/thednp/bootstrap.native`

**Comment by thednp** [comment]
As you suggested, I've cooked up an account at npm site https://www.npmjs.com/~thednp

You can transfer project as soon as you see fit :)

**Comment by IngwiePhoenix** [comment]
There you go! Check https://www.npmjs.com/package/bootstrap.native and see, you are now listed as owner too.

Don't get confused of the version, i had to add the version tag so it would let me update the package. :)

That other listing of `bootstrap.native` you found comes from a source i haven't seen before. It looks like a service that crawls NPM for packages. So I can not do anything there if their links get generated wrongly.

Also thanks for the crediting. :)

In order to publish to NPM or bower a new version, just navigate into the package and type

    npm/bower publish

NPM and Bower share the same set of commands.

**Comment by IngwiePhoenix** [comment]
Oh by the way, i should mention this. I brought this up for discussion on the Bootstrap Slack chat. They are considering less to no jQuery for bs4. But the bootstrap maintainers saw the project, so it looks like they have an open ear! Just thought I'd let you know. Been hanging out there for a couple of days now.

**Comment by IngwiePhoenix** [comment]
Also I just realized that my 0.9.7 tag didnt transfer while merging. You need to make a 0.9.7 tag, otherwise Bower won't pick it up too easy.

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/bootstrap.native $ git tag
0.9.2
0.9.3
0.9.4
0.9.5
0.9.6
0.9.7
Ingwie@Ingwies-Macbook-Pro.local ~/W/bootstrap.native $ cd ../dnp-bsn/; git tag
0.9.2
0.9.3
0.9.4
0.9.5
0.9.6
Ingwie@Ingwies-Macbook-Pro.local ~/W/dnp-bsn $ bower info bootstrap.native
bower bootstrap.native#*        cached git://github.com/thednp/bootstrap.native.git#0.9.6
bower bootstrap.native#*      validate 0.9.6 against git://github.com/thednp/bootstrap.native.git#*

{
  name: 'bootstrap.native',
  homepage: 'https://github.com/thednp/bootstrap.native',
  version: '0.9.6'
}

Available versions:
  - 0.9.6
  - 0.9.5
  - 0.9.4
  - 0.9.3
  - 0.9.2
```

**Comment by thednp** [comment]
So you think it's safe to go 0.9.7 release tag on git?

**Comment by IngwiePhoenix** [comment]
Definitively! I just integrated this into my bigger project. And the change is dramatic:

jQuery + Bootstrap JS + other stuff:	178 Kb minified
Cash + bootstrap.native + other stuff:	60 kb minified

Cash is a 15kb big alternative to jQuery that I use to do some dom manipulation. it really is just for convenience, but its so tiny, that i had to extend it to get $.ready and $.load to work at all. :)

So yeah, the 0.9.7 tag is very safe!

**Comment by thednp** [comment]
Alright then, we gonna have a CDN very soon.

**Comment by thednp** [comment]
There you have it, 0.9.7 release tag on CDN, congrats for your wonderful work :)

`<script type="text/javascript" src="https://cdn.jsdelivr.net/bootstrap.native/0.9.7/bootstrap-native.min.js"></script>`

**Pull request merged**
